runtime: nodejs10
env_variables:
  GHOST_KEY: $GHOST_KEY
  GHOST_URL: $GHOST_URL
  GHOST_VERSION: $GHOST_VERSION
  CONTENTFUL_SPACE: $CONTENTFUL_SPACE
  CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
  FRONTEND_URL: $FRONTEND_URL
