module.exports = credentials = {
    CONTENTFUL_SPACE: 'CONTENTFUL SPACE VALUE',
    CONTENTFUL_ACCESS_TOKEN: 'CONTENTFUL ACCESS TOKEN',
    CONTENTFUL_IMAGES: 'CONTENTFUL IMAGES URL',
    GHOST_URL: 'GHOST API URL',
    GHOST_KEY: 'GHOST API KEY',
    GHOST_VERSION: 'GHOST API VERSION'
};
