name: Deploy to App Engine

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Update app.yaml
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          GHOST_KEY: ${{ secrets.GHOST_KEY }}
          GHOST_URL: ${{ secrets.GHOST_URL }}
          GHOST_VERSION: ${{ secrets.GHOST_VERSION }}
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      - name: Deploy to App Engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: app deploy app.yaml
