name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - name: Test API
        run: npm run test
        env:
          GHOST_KEY: ${{ secrets.GHOST_KEY }}
          GHOST_URL: ${{ secrets.GHOST_URL }}
          GHOST_VERSION: ${{ secrets.GHOST_VERSION }}
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_IMAGES: ${{ secrets.CONTENTFUL_IMAGES }}
